import {
	ConvexClientProvider,
	JotaiProvider,
	ModalsProvider
} from '@/components/providers'
import { Toaster } from '@/components/ui'
import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Slack Clone',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ConvexAuthNextjsServerProvider>
			<html lang="en">
				<body className={inter.className}>
					<ConvexClientProvider>
						<JotaiProvider>
							<ModalsProvider />
							<Toaster />
							{children}
						</JotaiProvider>
					</ConvexClientProvider>
				</body>
			</html>
		</ConvexAuthNextjsServerProvider>
	)
}
